on:
  push:
  pull_request:

permissions:
  contents: read

name: Clippy and build
jobs:
  clippy:
    permissions:
      contents: read
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: rustup toolchain install stable
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - run: rustup toolchain install stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --profile release-lto
      - uses: actions/upload-artifact@v6
        with:
          name: mcman-${{ matrix.os }}
          path: |
            target/release/mcman*
            !target/release/mcman.d
